name: "Create new Project"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

# Essential for OIDC: Grants permission to request the JWT token from Azure
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: "Terraform Action"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./projects
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      BACKEND_RESOURCE_GROUP: ${{ secrets.BACKEND_RESOURCE_GROUP }}
      BACKEND_STORAGE_ACCOUNT: ${{ secrets.BACKEND_STORAGE_ACCOUNT }}
      BACKEND_CONTAINER: ${{ secrets.BACKEND_CONTAINER }}
      BACKEND_KEY: ${{ secrets.BACKEND_KEY }}

      ARM_USE_OIDC: true # Tells Terraform to use OIDC instead of a Secret

      TF_VAR_github_app_client_id: ${{ secrets.GH_APP_CLIENT_ID }}
      TF_VAR_github_app_installation_id: ${{ secrets.GH_APP_INSTALLATION_ID }}
      TF_VAR_github_app_pem_content: ${{ secrets.GH_APP_PRIVATE_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: "Terraform Version"
        id: version
        run: terraform --version

      - name: Terraform Init
        id: init
        run: |
          terraform init \
          -backend-config="resource_group_name=$BACKEND_RESOURCE_GROUP" \
          -backend-config="storage_account_name=$BACKEND_STORAGE_ACCOUNT" \
          -backend-config="container_name=$BACKEND_CONTAINER" \
          -backend-config="key=$BACKEND_KEY" \

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=terraform.tfplan -input=false -lock-timeout=300s

      - name: "Upload Terraform Plan to Working Directory"
        uses: actions/upload-artifact@v4
        with:
          name: terraformPlan
          path: "terraform.tfplan"

      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply terraform.tfplan

